# Force Ubuntu 16.04 "Xenial" to get newer GCC, binutils etc.
dist: xenial

addons:
    apt:
        packages:
           - autotools-dev
           - libtool
           - libgmp-dev
 
language: c
sudo: false
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
notifications:
  - email: true
script:
  - while sleep 30; do echo "still alive"; done &
  - ./autogen.sh
  - ./configure
  - make
  - make check
